name: bfloat16

on:
  push:
    branches:
      - master
      - v2
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Build the bproject
      run: (mkdir build && cd build && cmake ..)
    - name: Configure
      run: cmake --build ./build --config RELEASE
    - name: Run tests
      run: ./build/bin/tests